sudo: required

services:
  - docker

## Make sure all containers build without error.
#before_install: 
#  - docker build -t zeyanlin/r-ver r-ver
 

## A few simple / crude tests
script:
  - docker run -ti zeyanlin/r-ver R --version

  - docker run -d --name r-ver zeyanlin/r-ver
  - sleep 5 && docker ps | grep r-ver
  - docker rm -f $(docker ps -a -q)
